<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0-windows10.0.22000.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <RootNamespace>Glance.WorldClock.WinUI</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <DisableEmbeddedXbf>false</DisableEmbeddedXbf>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <DefaultLanguage>en</DefaultLanguage>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Include="Strings\**\*.resw" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Themes\WorldClock.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Elysium.UI.Controls.WinUI" Version="$(ElysiumVersion)" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glance.Application.Abstractions\Glance.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Glance.UI.WinUI\Glance.UI.WinUI.csproj" />
    <ProjectReference Include="..\Glance.WorldClock\Glance.WorldClock.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Themes\WorldClock.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>
