<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <RootNamespace>Glance.Assistant.WinUI</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <ImplicitUsings>enable</ImplicitUsings>
    <DisableEmbeddedXbf>false</DisableEmbeddedXbf>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <WindowsAppSDKSelfContainedAudit>false</WindowsAppSDKSelfContainedAudit>
    <Platforms>AnyCPU;x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <NoWarn>$(NoWarn);CS8305</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glance.Application.Abstractions\Glance.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Glance.Assistant\Glance.Assistant.csproj" />
  </ItemGroup>
  <Target Name="RestoreAssistantPriIndexName" AfterTargets="_OverrideGetPriIndexName">
    <PropertyGroup>
      <PriIndexName>$(TargetName)</PriIndexName>
    </PropertyGroup>
  </Target>
</Project>
